variable "region" {}
variable "cloudflare_api_key" {}
variable "cloudflare_email" {}
variable "s3_bucket_name" {}
variable "domain_name" {}
variable "cloudfront_comment" {}
variable "group_name" {}
variable "user_name" {}
variable "cloudflare_zone_id" {}
variable "cloudfront_oai_iam_arn" {}
